[[constraint]]
	name = "github.com/olivere/elastic"
	version = "6.2.11"

[[constraint]]
	name = "gopkg.in/urfave/cli.v1"
	version = "1.19.1"

[[constraint]]
    name = "github.com/inconshreveable/log15"
	branch = "master"

[[constraint]]
	name = "github.com/storozhukBM/verifier"
	branch = "master"

[[constraint]]
	name = "github.com/InVisionApp/go-logger"
	version = "1.0.1"

[[constraint]]
	name = "cloud.google.com/go"
	version = "0.25.0"

[[constraint]]
	name = "github.com/icrowley/fake"
	branch = "master"

[[constraint]]
	name = "github.com/mozillazg/go-unidecode"
	branch = "master"


[prune]
  #non-go = false
  go-tests = true
  unused-packages = true
